### PR TITLE
Add otel support

### PR DESCRIPTION
**Pull request by ligangty**
* Update parent to 2: upgrade the quarkus version to 2.11.2.Final
  * Add opentelemetry support

### CODE REVIEW

**Comment by ligangty** [comment]
@yma88 Seems the archive service is missing otel support yet. This commit will add it for further testing on devel. BTW, I've upgraded the service-parent to version 2 due to the otel extension support for quarkus.

**Comment by yma955** [comment]
@ligangty Hi, LGTM, only about the service-parent upgrade, we have tried that in 1.0.0, but the archive service stopped working by 'exceeding flow-control window' issue, which should be caused by Quarkus2 and it seems introducing an issue about netty and vertx handling on HTTP2.0, if we use Quarkus 1.12.2 it will not have this problem, I suppose it should be because Quarkus 1.12.2 doesn't support HTTP2.0 yet.
I'm not sure if the upgrade is necessary, if not, could we keep this version or do you have any suggestion?

**Comment by ligangty** [comment]
@yma88 I'm not sure if Quarkus 1 supports opentelemetry. I'll check that. But if it does not support, I think this upgrade will be necessary. 
For the   'exceeding flow-control window' issue, is it a reproducible issue or not? If yes, maybe we can find a workaround later.

**Comment by yma955** [comment]
@ligangty The issue failed to reproduce locally but I suppose that might be related to stream initial flow-control window size on the HTTP/2 connection, which should depend on the input size of the stream. Maybe we could try to reproduce it by some integration testing cases.
I agree we need to apply Quarkus2 for opentelemetry and feel free to merge this if necessary, I'll try to find the workaround for the flow-control window issue then.

**Comment by ligangty** [comment]
@yma88 Ok. I think we should create a new tag before this merge. I'll do it and let you know.

**Comment by ligangty** [comment]
@yma88 I've created a new branch 1.1.x and pushed PR there: https://github.com/Commonjava/indy-archive-service/pull/32, I'll close this PR. So let's leave 1.0.x for Quarkus 1.x.

**Pull request closed without merging**
