### PR TITLE
tracking report model, mapper and entry

### PR DESCRIPTION
**Pull request by shokakucarrier**

### CODE REVIEW

**Comment by shokakucarrier** [comment]
@yma88 Wait what? you've revoked your commit ?

**Comment by ligangty** [comment]
@shokakucarrier Let's hold this pr. After further thinking, I'm considering that the tracking report is also not needed in archive service because all needed info is enough in PNC's repos/paths file. 
Let's continue on the main function for this service, and when the tracking report is still needed, we can come back to this pr.
cc @yma88

**Comment by yma955** [comment]
> @shokakucarrier Let's hold this pr. After further thinking, I'm considering that the tracking report is also not needed in archive service because all needed info is enough in PNC's repos/paths file.
> Let's continue on the main function for this service, and when the tracking report is still needed, we can come back to this pr.
> cc @yma88

@ligangty Yes, agree, we just need to send the tracking report back to the main indy at one shot after sidecar build, then seal, no need to do anything in archive service.

**Comment by yma955** [comment]
> @yma88 Wait what? you've revoked your commit ?

@shokakucarrier 
Yes, I revoked and merged in the new PR, just because you don't understand why it's merged, although it was required by you in LAST THU. Whatever, next time no matter what the reason is, PR will be merged after all the comments are resolved and approved. I quite agree with it and follow years.

**Comment by shokakucarrier** [comment]
> > @yma88 Wait what? you've revoked your commit ?
> 
> @shokakucarrier
> Yes, I revoked and merged in the new PR, just because you don't understand why it's merged, although it was required by you in LAST THU. Whatever, next time no matter what the reason is, PR will be merged after all the comments are resolved and approved. I quite agree with it and follow years.

Thanks for explain it to me, apologize if I'm making any nonsense, I'm agreed that we can put this function here as a pr

**Comment by shokakucarrier** [comment]
conflicted and closed

**Pull request closed without merging**
